import { useMemo, useCallback, useEffect, useState } from 'react';
import { ErrorBoundary } from './components/ErrorBoundary/ErrorBoundary';
import { AppShell } from './components/AppShell/AppShell';
import { MapView } from './components/Map/MapView';
import { MapLegend } from './components/Map/MapLegend';
import { QuarterTimeline } from './components/Timeline/QuarterTimeline';
import { TractDetails } from './components/DetailsPanel/TractDetails';
import { ComparisonControls } from './components/ComparisonMode/ComparisonControls';
import { MetricSelector } from './components/MetricSelector/MetricSelector';
import { useMapData } from './hooks/useMapData';
import { useAppState } from './hooks/useAppState';
import {
  calculateQuantileBreaks,
  calculateAppreciationBreaks,
  MISSING_COLOR,
} from './data/classification';
import { calculateAppreciation, getSortedQuarterIds } from './data/formatters';

export default function App() {
  const { geometry, marketData, metadata, loading, error } = useMapData();
  const {
    state,
    setSelectedTract,
    setSelectedQuarter,
    setActiveMetric,
    enableComparison,
    disableComparison,
  } = useAppState(metadata?.dateCoverageEnd ?? '');

  const [isPlaying, setIsPlaying] = useState(false);

  // Fall back to last quarter when metadata loads
  useEffect(() => {
    if (metadata && !state.selectedQuarter) {
      setSelectedQuarter(metadata.dateCoverageEnd);
    }
  }, [metadata, state.selectedQuarter, setSelectedQuarter]);

  // Calculate legend breaks
  const breaks = useMemo(() => {
    if (!marketData || !state.selectedQuarter) return [];
    return calculateQuantileBreaks(marketData, state.selectedQuarter, state.activeMetric);
  }, [marketData, state.selectedQuarter, state.activeMetric]);

  // Comparison mode colors
  const comparisonColors = useMemo(() => {
    if (!marketData || !state.comparisonMode || !state.comparisonStartQuarter || !state.comparisonEndQuarter) {
      return null;
    }

    const appreciationMap = new Map<string, number | null>();
    const allTracts = new Set<string>();

    const startData = marketData[state.comparisonStartQuarter];
    const endData = marketData[state.comparisonEndQuarter];
    if (startData) Object.keys(startData).forEach(t => allTracts.add(t));
    if (endData) Object.keys(endData).forEach(t => allTracts.add(t));

    for (const tractId of allTracts) {
      const startRecord = startData?.[tractId] ?? null;
      const endRecord = endData?.[tractId] ?? null;
      const { percentageChange } = calculateAppreciation(startRecord, endRecord);
      appreciationMap.set(tractId, percentageChange);
    }

    const appBreaks = calculateAppreciationBreaks(appreciationMap);

    // Build color map by finding which break each percentage falls into
    const colorMap = new Map<string, string>();
    for (const [tractId, pct] of appreciationMap) {
      if (pct == null) {
        colorMap.set(tractId, MISSING_COLOR);
        continue;
      }
      let found = false;
      for (const b of appBreaks) {
        if (pct >= b.minValue && pct <= b.maxValue) {
          colorMap.set(tractId, b.color);
          found = true;
          break;
        }
      }
      if (!found && appBreaks.length > 0) {
        colorMap.set(tractId, appBreaks[appBreaks.length - 1].color);
      }
      if (!found && appBreaks.length === 0) {
        colorMap.set(tractId, MISSING_COLOR);
      }
    }

    return colorMap;
  }, [marketData, state.comparisonMode, state.comparisonStartQuarter, state.comparisonEndQuarter]);

  // Get selected tract name from geometry
  const tractName = useMemo(() => {
    if (!state.selectedTract || !geometry) return null;
    const feature = geometry.features.find(f => f.properties.tract_geoid === state.selectedTract);
    return feature?.properties.tract_name ?? state.selectedTract;
  }, [state.selectedTract, geometry]);

  // Play animation
  useEffect(() => {
    if (!isPlaying || !marketData) return;
    const quarters = getSortedQuarterIds(marketData);
    const currentIdx = quarters.indexOf(state.selectedQuarter);

    if (currentIdx >= quarters.length - 1) {
      setIsPlaying(false);
      return;
    }

    const timeout = window.setTimeout(() => {
      const nextIdx = currentIdx + 1;
      if (nextIdx < quarters.length) {
        setSelectedQuarter(quarters[nextIdx]);
      } else {
        setIsPlaying(false);
      }
    }, 1200);

    return () => window.clearTimeout(timeout);
  }, [isPlaying, marketData, state.selectedQuarter, setSelectedQuarter]);

  const handlePlayToggle = useCallback(() => {
    setIsPlaying(prev => !prev);
  }, []);

  if (error) {
    return (
      <div role="alert" style={{ padding: '2rem', textAlign: 'center' }}>
        <h2>Unable to load data</h2>
        <p>{error}</p>
        <p>Make sure <code>public/data/</code> assets have been generated by the publish stage.</p>
      </div>
    );
  }

  if (loading === 'loading' || loading === 'idle') {
    return (
      <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh' }}>
        <p style={{ fontSize: '1.2rem', color: '#666' }}>Loading St. Petersburg housing data…</p>
      </div>
    );
  }

  return (
    <ErrorBoundary>
      <AppShell
        mapPanel={
          <div style={{ position: 'relative', width: '100%', height: '100%' }}>
            <MapView
              geometry={geometry}
              marketData={marketData}
              selectedQuarter={state.selectedQuarter}
              selectedTract={state.selectedTract}
              activeMetric={state.activeMetric}
              breaks={breaks}
              comparisonMode={state.comparisonMode}
              comparisonColors={comparisonColors}
              onSelectTract={setSelectedTract}
            />
            <MapLegend
              metric={state.activeMetric}
              breaks={breaks}
              comparisonMode={state.comparisonMode}
            />
          </div>
        }
        detailsPanel={
          <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
            <div style={{ padding: '0.5rem', borderBottom: '1px solid #e0e0e0' }}>
              <MetricSelector
                value={state.activeMetric}
                onChange={setActiveMetric}
                disabled={loading !== 'loaded'}
              />
            </div>
            <ComparisonControls
              marketData={marketData}
              enabled={state.comparisonMode}
              startQuarter={state.comparisonStartQuarter}
              endQuarter={state.comparisonEndQuarter}
              onEnable={enableComparison}
              onDisable={disableComparison}
              disabled={loading !== 'loaded'}
            />
            <div style={{ flex: 1, overflowY: 'auto' }}>
              <TractDetails
                tractGeoid={state.selectedTract}
                tractName={tractName}
                selectedQuarter={state.selectedQuarter}
                marketData={marketData}
                metadata={metadata}
              />
            </div>
          </div>
        }
        timeline={
          <QuarterTimeline
            marketData={marketData}
            selectedQuarter={state.selectedQuarter}
            disabled={loading !== 'loaded'}
            onChangeQuarter={setSelectedQuarter}
            onPlayToggle={handlePlayToggle}
            isPlaying={isPlaying}
          />
        }
      />
    </ErrorBoundary>
  );
}
