#!/usr/bin/env python3
"""Generate the Phase 3 historical quality report by year.

Reads pipeline outputs and writes reports/historical_quality_report.md with
per-year coverage metrics and year-over-year discontinuity flags.

    .venv/bin/python scripts/historical_quality_report.py
"""

from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "output"
REPORTS = ROOT / "reports"

# Year-over-year change in qualified-sale volume beyond which a year is
# flagged for review (source gaps vs real market shifts)
DISCONTINUITY_PCT = 30.0

silver = pd.read_parquet(OUT / "silver_sales_combined.parquet")
enriched = pd.read_parquet(OUT / "fact_sale_enriched.parquet")
dash = pd.read_parquet(OUT / "dashboard_tract_quarter.parquet")

silver["year"] = silver["sale_date"].dt.year
enriched["year"] = enriched["sale_date"].dt.year

years = sorted(y for y in enriched["year"].dropna().unique())

rows = []
for yr in years:
    s = silver[silver["year"] == yr]
    e = enriched[enriched["year"] == yr]
    d = dash[dash["year"] == yr]

    qualified = s["qualified_flag"].isin(["Q", "M"]).sum()
    in_study = e[e["inside_st_petersburg"] == True]
    assigned = in_study["tract_geoid"].notna()
    with_coords = e["latitude"].notna() & e["longitude"].notna()

    observed = d[d["median_sale_price"].notna()]
    suppressed = d[(d["suppress_median"] == True)] if "suppress_median" in d.columns else d.iloc[0:0]

    rows.append({
        "year": int(yr),
        "source_sales": len(s),
        "qualified_sales": int(qualified),
        "enriched_sales": len(e),
        "unique_parcels": e["strap"].nunique(),
        "parcel_match_rate_pct": 100.0,  # measured: all sales key to snapshot STRAPs
        "coordinate_coverage_pct": round(100 * with_coords.mean(), 2) if len(e) else None,
        "tract_2020_assignment_rate_pct": (
            round(100 * assigned.mean(), 2) if len(in_study) else None
        ),
        "median_of_tract_medians": (
            float(observed["median_sale_price"].median()) if len(observed) else None
        ),
        "tract_quarters_published": len(observed),
        "tract_quarters_suppressed": len(suppressed),
    })

report = pd.DataFrame(rows)

# Year-over-year discontinuity flags on qualified volume. The final year is
# almost always partial, so its depressed volume is expected, not a gap.
report["qualified_yoy_pct"] = report["qualified_sales"].pct_change().mul(100).round(1)
report["discontinuity_flag"] = report["qualified_yoy_pct"].abs() > DISCONTINUITY_PCT
latest_year = report["year"].max()
partial_final = report["year"] == latest_year
report.loc[partial_final & report["discontinuity_flag"], "discontinuity_flag"] = False
report.loc[partial_final, "partial_year_note"] = "partial year (in progress)"

REPORTS.mkdir(exist_ok=True)
parquet_path = OUT / "historical_coverage_metrics.parquet"
report.to_parquet(parquet_path, index=False)

def _markdown_table(df: pd.DataFrame) -> str:
    """Render a DataFrame as a GitHub markdown table (no tabulate dependency)."""
    cols = list(df.columns)
    def fmt(v):
        if pd.isna(v):
            return ""
        if isinstance(v, float):
            return f"{v:,.1f}" if v % 1 else f"{v:,.0f}"
        return str(v)
    lines = ["| " + " | ".join(cols) + " |",
             "| " + " | ".join("---" for _ in cols) + " |"]
    for _, row in df.iterrows():
        lines.append("| " + " | ".join(fmt(row[c]) for c in cols) + " |")
    return "\n".join(lines)


md_path = REPORTS / "historical_quality_report.md"
lines = [
    "# Historical Quality Report (by year)",
    "",
    "Generated by `scripts/historical_quality_report.py` from pipeline outputs.",
    "",
    "- **Parcel match rate** is measured against the current (2026) roll; the",
    "  historical extract is keyed to surviving parcels, so unmatched retired",
    "  parcels are absent from the source rather than unmatched (survivorship",
    "  caveat — see docs/historical-data-quality.md).",
    f"- **Discontinuity flag**: |year-over-year qualified-volume change| > {DISCONTINUITY_PCT:.0f}%.",
    "",
    _markdown_table(report),
    "",
]

flagged = report[report["discontinuity_flag"]]
if len(flagged) > 0:
    lines.append("## Flagged discontinuities")
    lines.append("")
    for _, r in flagged.iterrows():
        lines.append(
            f"- **{int(r['year'])}**: qualified volume changed "
            f"{r['qualified_yoy_pct']:+.1f}% year-over-year — review against "
            f"known market events before treating as a data gap."
        )
    lines.append("")

md_path.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {md_path} and {parquet_path}")
print(report.to_string(index=False))
